export default {
  inputRef: document.querySelector('.main__form'),
  bookmarkRef: document.querySelector('.main__bookmarks'),
  bookmarkBtnRef: document.querySelector('.main__bookmarkBtn'),
  dataBlockRef: document.querySelector('.data'),
  fiveDaysRef: document.querySelector('.five__days'),
  oneDaySection: document.querySelector('.one-day-section'),
  locationName: document.getElementById('locationName'),
  locationWeather: document.getElementById('locationWeather'),
  todayTemperature: document.getElementById('todayTemperature'),
  todayMinTemperature: document.getElementById('todayMinTemperature'),
  todayMaxTemperature: document.getElementById('todayMaxTemperature'),
  weatherBlock: document.querySelector('.weather'),
  commentTextContent: document.querySelector('.comments__content'),
};
