export default {
  inputRef: document.querySelector('.input-section__form'),
  bookmarkRef: document.querySelector('.bookmarks__list'),
  bookmarkBtnRef: document.querySelector('.input-section__bookmarkBtn'),
  dataBlockRef: document.querySelector('.data'),
  fiveDaysRef: document.querySelector('.five__days'),
  oneDaySection: document.querySelector('.one-day-section'),
  locationName: document.getElementById('locationName'),
  locationWeather: document.getElementById('locationWeather'),
  todayTemperature: document.getElementById('todayTemperature'),
  todayMinTemperature: document.getElementById('todayMinTemperature'),
  todayMaxTemperature: document.getElementById('todayMaxTemperature'),
  weatherBlock: document.querySelector('.weather'),
  commentTextContent: document.querySelector('.comments__content'),
};
